version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    "*.env",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.service",
    "go.mk.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

